/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuan_vision_ndkdemo_MainActivity */

#ifndef _Included_com_kuan_vision_ndkdemo_MainActivity
#define _Included_com_kuan_vision_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuan_vision_ndkdemo_MainActivity
 * Method:    grapyproc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kuan_vision_ndkdemo_MainActivity_grapyproc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
