/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuan_vision_ndkdemo_NativeMethod */

#ifndef _Included_com_kuan_vision_ndkdemo_NativeMethod
#define _Included_com_kuan_vision_ndkdemo_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuan_vision_ndkdemo_NativeMethod
 * Method:    getStrinFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kuan_vision_ndkdemo_NativeMethod_getStrinFromC
  (JNIEnv *env, jclass obj)
  {
    env->NewStringUTF("Hello Jni. Once more!");
  }


#ifdef __cplusplus
}
#endif
#endif
